# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:08:37+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class CrawledUrl(BaseModel):
    body: Optional[str] = Field(
        None, description='The body of the request that was used to visit the URL.'
    )
    httpMethod: Optional[str] = Field(
        None,
        description='The http method of the request that was used to visit the URL, in uppercase.',
    )
    url: Optional[str] = Field(None, description='The URL that was crawled.')


class CustomAccount(BaseModel):
    loginUrl: Optional[str] = Field(
        None, description='Required. The login form URL of the website.'
    )
    password: Optional[str] = Field(
        None,
        description='Required. Input only. The password of the custom account. The credential is stored encrypted and not returned in any response nor included in audit logs.',
    )
    username: Optional[str] = Field(
        None, description='Required. The user name of the custom account.'
    )


class Empty(BaseModel):
    pass


class Severity(Enum):
    SEVERITY_UNSPECIFIED = 'SEVERITY_UNSPECIFIED'
    CRITICAL = 'CRITICAL'
    HIGH = 'HIGH'
    MEDIUM = 'MEDIUM'
    LOW = 'LOW'


class FindingTypeStats(BaseModel):
    findingCount: Optional[int] = Field(
        None, description='The count of findings belonging to this finding type.'
    )
    findingType: Optional[str] = Field(
        None, description='The finding type associated with the stats.'
    )


class Form(BaseModel):
    actionUri: Optional[str] = Field(
        None, description="! The URI where to send the form when it's submitted."
    )
    fields: Optional[List[str]] = Field(
        None, description='! The names of form fields related to the vulnerability.'
    )


class GoogleAccount(BaseModel):
    password: Optional[str] = Field(
        None,
        description='Required. Input only. The password of the Google account. The credential is stored encrypted and not returned in any response nor included in audit logs.',
    )
    username: Optional[str] = Field(
        None, description='Required. The user name of the Google account.'
    )


class Header(BaseModel):
    name: Optional[str] = Field(None, description='Header name.')
    value: Optional[str] = Field(None, description='Header value.')


class IapTestServiceAccountInfo(BaseModel):
    targetAudienceClientId: Optional[str] = Field(
        None,
        description='Required. Describes OAuth2 Client ID of resources protected by Identity-Aware-Proxy(IAP).',
    )


class ListCrawledUrlsResponse(BaseModel):
    crawledUrls: Optional[List[CrawledUrl]] = Field(
        None, description='The list of CrawledUrls returned.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Token to retrieve the next page of results, or empty if there are no more results in the list.',
    )


class ListFindingTypeStatsResponse(BaseModel):
    findingTypeStats: Optional[List[FindingTypeStats]] = Field(
        None, description='The list of FindingTypeStats returned.'
    )


class OutdatedLibrary(BaseModel):
    learnMoreUrls: Optional[List[str]] = Field(
        None,
        description='URLs to learn more information about the vulnerabilities in the library.',
    )
    libraryName: Optional[str] = Field(
        None, description='The name of the outdated library.'
    )
    version: Optional[str] = Field(None, description='The version number.')


class ExportToSecurityCommandCenter(Enum):
    EXPORT_TO_SECURITY_COMMAND_CENTER_UNSPECIFIED = (
        'EXPORT_TO_SECURITY_COMMAND_CENTER_UNSPECIFIED'
    )
    ENABLED = 'ENABLED'
    DISABLED = 'DISABLED'


class RiskLevel(Enum):
    RISK_LEVEL_UNSPECIFIED = 'RISK_LEVEL_UNSPECIFIED'
    NORMAL = 'NORMAL'
    LOW = 'LOW'


class TargetPlatform(Enum):
    TARGET_PLATFORM_UNSPECIFIED = 'TARGET_PLATFORM_UNSPECIFIED'
    APP_ENGINE = 'APP_ENGINE'
    COMPUTE = 'COMPUTE'
    CLOUD_RUN = 'CLOUD_RUN'
    CLOUD_FUNCTIONS = 'CLOUD_FUNCTIONS'


class UserAgent(Enum):
    USER_AGENT_UNSPECIFIED = 'USER_AGENT_UNSPECIFIED'
    CHROME_LINUX = 'CHROME_LINUX'
    CHROME_ANDROID = 'CHROME_ANDROID'
    SAFARI_IPHONE = 'SAFARI_IPHONE'


class Code(Enum):
    CODE_UNSPECIFIED = 'CODE_UNSPECIFIED'
    OK = 'OK'
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    APPENGINE_API_BACKEND_ERROR = 'APPENGINE_API_BACKEND_ERROR'
    APPENGINE_API_NOT_ACCESSIBLE = 'APPENGINE_API_NOT_ACCESSIBLE'
    APPENGINE_DEFAULT_HOST_MISSING = 'APPENGINE_DEFAULT_HOST_MISSING'
    CANNOT_USE_GOOGLE_COM_ACCOUNT = 'CANNOT_USE_GOOGLE_COM_ACCOUNT'
    CANNOT_USE_OWNER_ACCOUNT = 'CANNOT_USE_OWNER_ACCOUNT'
    COMPUTE_API_BACKEND_ERROR = 'COMPUTE_API_BACKEND_ERROR'
    COMPUTE_API_NOT_ACCESSIBLE = 'COMPUTE_API_NOT_ACCESSIBLE'
    CUSTOM_LOGIN_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT = (
        'CUSTOM_LOGIN_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT'
    )
    CUSTOM_LOGIN_URL_MALFORMED = 'CUSTOM_LOGIN_URL_MALFORMED'
    CUSTOM_LOGIN_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS = (
        'CUSTOM_LOGIN_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS'
    )
    CUSTOM_LOGIN_URL_MAPPED_TO_UNRESERVED_ADDRESS = (
        'CUSTOM_LOGIN_URL_MAPPED_TO_UNRESERVED_ADDRESS'
    )
    CUSTOM_LOGIN_URL_HAS_NON_ROUTABLE_IP_ADDRESS = (
        'CUSTOM_LOGIN_URL_HAS_NON_ROUTABLE_IP_ADDRESS'
    )
    CUSTOM_LOGIN_URL_HAS_UNRESERVED_IP_ADDRESS = (
        'CUSTOM_LOGIN_URL_HAS_UNRESERVED_IP_ADDRESS'
    )
    DUPLICATE_SCAN_NAME = 'DUPLICATE_SCAN_NAME'
    INVALID_FIELD_VALUE = 'INVALID_FIELD_VALUE'
    FAILED_TO_AUTHENTICATE_TO_TARGET = 'FAILED_TO_AUTHENTICATE_TO_TARGET'
    FINDING_TYPE_UNSPECIFIED = 'FINDING_TYPE_UNSPECIFIED'
    FORBIDDEN_TO_SCAN_COMPUTE = 'FORBIDDEN_TO_SCAN_COMPUTE'
    FORBIDDEN_UPDATE_TO_MANAGED_SCAN = 'FORBIDDEN_UPDATE_TO_MANAGED_SCAN'
    MALFORMED_FILTER = 'MALFORMED_FILTER'
    MALFORMED_RESOURCE_NAME = 'MALFORMED_RESOURCE_NAME'
    PROJECT_INACTIVE = 'PROJECT_INACTIVE'
    REQUIRED_FIELD = 'REQUIRED_FIELD'
    RESOURCE_NAME_INCONSISTENT = 'RESOURCE_NAME_INCONSISTENT'
    SCAN_ALREADY_RUNNING = 'SCAN_ALREADY_RUNNING'
    SCAN_NOT_RUNNING = 'SCAN_NOT_RUNNING'
    SEED_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT = (
        'SEED_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT'
    )
    SEED_URL_MALFORMED = 'SEED_URL_MALFORMED'
    SEED_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS = 'SEED_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS'
    SEED_URL_MAPPED_TO_UNRESERVED_ADDRESS = 'SEED_URL_MAPPED_TO_UNRESERVED_ADDRESS'
    SEED_URL_HAS_NON_ROUTABLE_IP_ADDRESS = 'SEED_URL_HAS_NON_ROUTABLE_IP_ADDRESS'
    SEED_URL_HAS_UNRESERVED_IP_ADDRESS = 'SEED_URL_HAS_UNRESERVED_IP_ADDRESS'
    SERVICE_ACCOUNT_NOT_CONFIGURED = 'SERVICE_ACCOUNT_NOT_CONFIGURED'
    TOO_MANY_SCANS = 'TOO_MANY_SCANS'
    UNABLE_TO_RESOLVE_PROJECT_INFO = 'UNABLE_TO_RESOLVE_PROJECT_INFO'
    UNSUPPORTED_BLACKLIST_PATTERN_FORMAT = 'UNSUPPORTED_BLACKLIST_PATTERN_FORMAT'
    UNSUPPORTED_FILTER = 'UNSUPPORTED_FILTER'
    UNSUPPORTED_FINDING_TYPE = 'UNSUPPORTED_FINDING_TYPE'
    UNSUPPORTED_URL_SCHEME = 'UNSUPPORTED_URL_SCHEME'


class ScanConfigError(BaseModel):
    code: Optional[Code] = Field(
        None, description='Indicates the reason code for a configuration failure.'
    )
    fieldName: Optional[str] = Field(
        None,
        description='Indicates the full name of the ScanConfig field that triggers this error, for example "scan_config.max_qps". This field is provided for troubleshooting purposes only and its actual value can change in the future.',
    )


class ExecutionState(Enum):
    EXECUTION_STATE_UNSPECIFIED = 'EXECUTION_STATE_UNSPECIFIED'
    QUEUED = 'QUEUED'
    SCANNING = 'SCANNING'
    FINISHED = 'FINISHED'


class ResultState(Enum):
    RESULT_STATE_UNSPECIFIED = 'RESULT_STATE_UNSPECIFIED'
    SUCCESS = 'SUCCESS'
    ERROR = 'ERROR'
    KILLED = 'KILLED'


class Code1(Enum):
    CODE_UNSPECIFIED = 'CODE_UNSPECIFIED'
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    SCAN_CONFIG_ISSUE = 'SCAN_CONFIG_ISSUE'
    AUTHENTICATION_CONFIG_ISSUE = 'AUTHENTICATION_CONFIG_ISSUE'
    TIMED_OUT_WHILE_SCANNING = 'TIMED_OUT_WHILE_SCANNING'
    TOO_MANY_REDIRECTS = 'TOO_MANY_REDIRECTS'
    TOO_MANY_HTTP_ERRORS = 'TOO_MANY_HTTP_ERRORS'
    STARTING_URLS_CRAWL_HTTP_ERRORS = 'STARTING_URLS_CRAWL_HTTP_ERRORS'


class ScanRunErrorTrace(BaseModel):
    code: Optional[Code1] = Field(None, description='Indicates the error reason code.')
    mostCommonHttpErrorCode: Optional[int] = Field(
        None,
        description='If the scan encounters TOO_MANY_HTTP_ERRORS, this field indicates the most common HTTP error code, if such is available. For example, if this code is 404, the scan has encountered too many NOT_FOUND responses.',
    )
    scanConfigError: Optional[ScanConfigError] = Field(
        None,
        description='If the scan encounters SCAN_CONFIG_ISSUE error, this field has the error message encountered during scan configuration validation that is performed before each scan run.',
    )


class Code2(Enum):
    CODE_UNSPECIFIED = 'CODE_UNSPECIFIED'
    INSUFFICIENT_CRAWL_RESULTS = 'INSUFFICIENT_CRAWL_RESULTS'
    TOO_MANY_CRAWL_RESULTS = 'TOO_MANY_CRAWL_RESULTS'
    TOO_MANY_FUZZ_TASKS = 'TOO_MANY_FUZZ_TASKS'
    BLOCKED_BY_IAP = 'BLOCKED_BY_IAP'
    NO_STARTING_URL_FOUND_FOR_MANAGED_SCAN = 'NO_STARTING_URL_FOUND_FOR_MANAGED_SCAN'


class ScanRunWarningTrace(BaseModel):
    code: Optional[Code2] = Field(None, description='Indicates the warning code.')


class Schedule(BaseModel):
    intervalDurationDays: Optional[int] = Field(
        None, description='Required. The duration of time between executions in days.'
    )
    scheduleTime: Optional[str] = Field(
        None,
        description='A timestamp indicates when the next run will be scheduled. The value is refreshed by the server after each run. If unspecified, it will default to current server time, which means the scan will be scheduled to start immediately.',
    )


class StartScanRunRequest(BaseModel):
    pass


class StopScanRunRequest(BaseModel):
    pass


class ViolatingResource(BaseModel):
    contentType: Optional[str] = Field(
        None, description='The MIME type of this resource.'
    )
    resourceUrl: Optional[str] = Field(
        None, description='URL of this violating resource.'
    )


class VulnerableHeaders(BaseModel):
    headers: Optional[List[Header]] = Field(
        None, description='List of vulnerable headers.'
    )
    missingHeaders: Optional[List[Header]] = Field(
        None, description='List of missing headers.'
    )


class VulnerableParameters(BaseModel):
    parameterNames: Optional[List[str]] = Field(
        None, description='The vulnerable parameter names.'
    )


class Xss(BaseModel):
    errorMessage: Optional[str] = Field(
        None, description='An error message generated by a javascript breakage.'
    )
    stackTraces: Optional[List[str]] = Field(
        None, description='Stack traces leading to the point where the XSS occurred.'
    )


class PayloadLocation(Enum):
    LOCATION_UNSPECIFIED = 'LOCATION_UNSPECIFIED'
    COMPLETE_REQUEST_BODY = 'COMPLETE_REQUEST_BODY'


class Xxe(BaseModel):
    payloadLocation: Optional[PayloadLocation] = Field(
        None, description='Location within the request where the payload was placed.'
    )
    payloadValue: Optional[str] = Field(
        None,
        description='The XML string that triggered the XXE vulnerability. Non-payload values might be redacted.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class Finding(BaseModel):
    body: Optional[str] = Field(
        None, description='The body of the request that triggered the vulnerability.'
    )
    description: Optional[str] = Field(
        None, description='The description of the vulnerability.'
    )
    finalUrl: Optional[str] = Field(
        None,
        description='The URL where the browser lands when the vulnerability is detected.',
    )
    findingType: Optional[str] = Field(
        None,
        description='The type of the Finding. Detailed and up-to-date information on findings can be found here: https://cloud.google.com/security-command-center/docs/how-to-remediate-web-security-scanner',
    )
    form: Optional[Form] = Field(
        None,
        description='An addon containing information reported for a vulnerability with an HTML form, if any.',
    )
    frameUrl: Optional[str] = Field(
        None,
        description='If the vulnerability was originated from nested IFrame, the immediate parent IFrame is reported.',
    )
    fuzzedUrl: Optional[str] = Field(
        None,
        description='The URL produced by the server-side fuzzer and used in the request that triggered the vulnerability.',
    )
    httpMethod: Optional[str] = Field(
        None,
        description='The http method of the request that triggered the vulnerability, in uppercase.',
    )
    name: Optional[str] = Field(
        None,
        description="The resource name of the Finding. The name follows the format of 'projects/{projectId}/scanConfigs/{scanConfigId}/scanruns/{scanRunId}/findings/{findingId}'. The finding IDs are generated by the system.",
    )
    outdatedLibrary: Optional[OutdatedLibrary] = Field(
        None, description='An addon containing information about outdated libraries.'
    )
    reproductionUrl: Optional[str] = Field(
        None,
        description='The URL containing human-readable payload that user can leverage to reproduce the vulnerability.',
    )
    severity: Optional[Severity] = Field(
        None, description='The severity level of the reported vulnerability.'
    )
    trackingId: Optional[str] = Field(
        None,
        description='The tracking ID uniquely identifies a vulnerability instance across multiple ScanRuns.',
    )
    violatingResource: Optional[ViolatingResource] = Field(
        None,
        description='An addon containing detailed information regarding any resource causing the vulnerability such as JavaScript sources, image, audio files, etc.',
    )
    vulnerableHeaders: Optional[VulnerableHeaders] = Field(
        None,
        description='An addon containing information about vulnerable or missing HTTP headers.',
    )
    vulnerableParameters: Optional[VulnerableParameters] = Field(
        None,
        description='An addon containing information about request parameters which were found to be vulnerable.',
    )
    xss: Optional[Xss] = Field(
        None, description='An addon containing information reported for an XSS, if any.'
    )
    xxe: Optional[Xxe] = Field(
        None, description='An addon containing information reported for an XXE, if any.'
    )


class IapCredential(BaseModel):
    iapTestServiceAccountInfo: Optional[IapTestServiceAccountInfo] = Field(
        None,
        description='Authentication configuration when Web-Security-Scanner service account is added in Identity-Aware-Proxy (IAP) access policies.',
    )


class ListFindingsResponse(BaseModel):
    findings: Optional[List[Finding]] = Field(
        None, description='The list of Findings returned.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Token to retrieve the next page of results, or empty if there are no more results in the list.',
    )


class ScanRun(BaseModel):
    endTime: Optional[str] = Field(
        None,
        description='The time at which the ScanRun reached termination state - that the ScanRun is either finished or stopped by user.',
    )
    errorTrace: Optional[ScanRunErrorTrace] = Field(
        None,
        description="If result_state is an ERROR, this field provides the primary reason for scan's termination and more details, if such are available.",
    )
    executionState: Optional[ExecutionState] = Field(
        None, description='The execution state of the ScanRun.'
    )
    hasVulnerabilities: Optional[bool] = Field(
        None, description='Whether the scan run has found any vulnerabilities.'
    )
    name: Optional[str] = Field(
        None,
        description="The resource name of the ScanRun. The name follows the format of 'projects/{projectId}/scanConfigs/{scanConfigId}/scanRuns/{scanRunId}'. The ScanRun IDs are generated by the system.",
    )
    progressPercent: Optional[int] = Field(
        None,
        description='The percentage of total completion ranging from 0 to 100. If the scan is in queue, the value is 0. If the scan is running, the value ranges from 0 to 100. If the scan is finished, the value is 100.',
    )
    resultState: Optional[ResultState] = Field(
        None,
        description='The result state of the ScanRun. This field is only available after the execution state reaches "FINISHED".',
    )
    startTime: Optional[str] = Field(
        None, description='The time at which the ScanRun started.'
    )
    urlsCrawledCount: Optional[str] = Field(
        None,
        description='The number of URLs crawled during this ScanRun. If the scan is in progress, the value represents the number of URLs crawled up to now.',
    )
    urlsTestedCount: Optional[str] = Field(
        None,
        description='The number of URLs tested during this ScanRun. If the scan is in progress, the value represents the number of URLs tested up to now. The number of URLs tested is usually larger than the number URLS crawled because typically a crawled URL is tested with multiple test payloads.',
    )
    warningTraces: Optional[List[ScanRunWarningTrace]] = Field(
        None,
        description='A list of warnings, if such are encountered during this scan run.',
    )


class Authentication(BaseModel):
    customAccount: Optional[CustomAccount] = Field(
        None, description='Authentication using a custom account.'
    )
    googleAccount: Optional[GoogleAccount] = Field(
        None, description='Authentication using a Google account.'
    )
    iapCredential: Optional[IapCredential] = Field(
        None, description='Authentication using Identity-Aware-Proxy (IAP).'
    )


class ListScanRunsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='Token to retrieve the next page of results, or empty if there are no more results in the list.',
    )
    scanRuns: Optional[List[ScanRun]] = Field(
        None, description='The list of ScanRuns returned.'
    )


class ScanConfig(BaseModel):
    authentication: Optional[Authentication] = Field(
        None,
        description='The authentication configuration. If specified, service will use the authentication configuration during scanning.',
    )
    blacklistPatterns: Optional[List[str]] = Field(
        None,
        description='The excluded URL patterns as described in https://cloud.google.com/security-command-center/docs/how-to-use-web-security-scanner#excluding_urls',
    )
    displayName: Optional[str] = Field(
        None, description='Required. The user provided display name of the ScanConfig.'
    )
    exportToSecurityCommandCenter: Optional[ExportToSecurityCommandCenter] = Field(
        None,
        description='Controls export of scan configurations and results to Security Command Center.',
    )
    ignoreHttpStatusErrors: Optional[bool] = Field(
        None,
        description='Whether to keep scanning even if most requests return HTTP error codes.',
    )
    latestRun: Optional[ScanRun] = Field(
        None, description='Latest ScanRun if available.'
    )
    managedScan: Optional[bool] = Field(
        None,
        description='Whether the scan config is managed by Web Security Scanner, output only.',
    )
    maxQps: Optional[int] = Field(
        None,
        description='The maximum QPS during scanning. A valid value ranges from 5 to 20 inclusively. If the field is unspecified or its value is set 0, server will default to 15. Other values outside of [5, 20] range will be rejected with INVALID_ARGUMENT error.',
    )
    name: Optional[str] = Field(
        None,
        description="The resource name of the ScanConfig. The name follows the format of 'projects/{projectId}/scanConfigs/{scanConfigId}'. The ScanConfig IDs are generated by the system.",
    )
    riskLevel: Optional[RiskLevel] = Field(
        None, description='The risk level selected for the scan'
    )
    schedule: Optional[Schedule] = Field(
        None, description='The schedule of the ScanConfig.'
    )
    startingUrls: Optional[List[str]] = Field(
        None,
        description='Required. The starting URLs from which the scanner finds site pages.',
    )
    staticIpScan: Optional[bool] = Field(
        None,
        description='Whether the scan configuration has enabled static IP address scan feature. If enabled, the scanner will access applications from static IP addresses.',
    )
    targetPlatforms: Optional[List[TargetPlatform]] = Field(
        None,
        description='Set of Google Cloud platforms targeted by the scan. If empty, APP_ENGINE will be used as a default.',
    )
    userAgent: Optional[UserAgent] = Field(
        None, description='The user agent used during scanning.'
    )


class ListScanConfigsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='Token to retrieve the next page of results, or empty if there are no more results in the list.',
    )
    scanConfigs: Optional[List[ScanConfig]] = Field(
        None, description='The list of ScanConfigs returned.'
    )
